# Site settings
title: Rafael Verona
description: 'Business Card Page'
url: 'https://raverona.github.io/'
baseurl: ''
profilepic: '/images/profile.jpg'
bkimage: '/images/cover.png'
#google_analytics: UA-XXXXXX-X
font_awesome: 'XXXXXXXXXX.js'

author:
  name: 'Rafael Verona'
  email: rafael.verona@nubank.com.br
  twitter_username: raverona
#  facebook_username:
  github_username:  raverona
  linkedin_username:  rafael-verona

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
